### ISSUE TITLE
Need file separator '\' to '/' in Windows.

### ISSUE THREAD

**Issue by qwerty2501** [laco0416/gulp-tsconfig-update#1]
Hello.
I use this plugin in Windows10.
but output path's file separator is '\'.
I guess, this behavior will make problem.
Please replace file separator to '/'.

Thank you.

**Comment by lacolaco** [comment]
@qwerty2501 I think you're right. so, I'd like to see your broken tsconfig.json.
thanks!

**Comment by lacolaco** [comment]
@qwerty2501 
A new version supoorts windows is published as beta.
please run `npm install gulp-tsconfig-update@beta` and try in windows again.

**Comment by qwerty2501** [comment]
See this broken file.
![tsconfig_broken](https://cloud.githubusercontent.com/assets/939468/9760636/c780bc36-5731-11e5-8a78-b70963d7718f.gif)

**Comment by qwerty2501** [comment]
I didn't succeed update tsconfig.json.
This behavior still occurs.

**Comment by lacolaco** [comment]
@qwerty2501 I have published v1.0.8-0 as `gulp-tsconfig-update@pre`. please try again!

**Comment by qwerty2501** [comment]
The string's replacing method can replace only one time.
You need to modified like this.

replace("\","/");

to

replace(/\\/g,"/");

sorry for my research is not good.

**Comment by lacolaco** [comment]
@qwerty2501 ok, please try v1.0.8-2 with `@pre`!

**Comment by qwerty2501** [comment]
I was confirmed that the it has been modified.
Its behavior is correct.
Thank you.

**Comment by lacolaco** [comment]
thanks mate!
